### ISSUE TITLE
next.js not working

### ISSUE THREAD

**Issue by msglab** [DylanVann/perfect-dark-mode#2]
it doesn't do anything int he demo (loads dark for me and clicking the button doesn't do anything). And the same happened when I installed it.

**Comment by DylanVann** [comment]
Hello @msglab , there was a bug in the CSS for that example, it was working on Chrome, but not mobile Safari.

This fixes it: https://github.com/DylanVann/perfect-dark-mode/commit/909b033b4d213a44dbc395776a9b054fe9376f74

The problem was the specificity of the `.pdm-light` selector was the same as the `@media (prefers-color-scheme: dark)` selector, and since the `@media (prefers-color-scheme: dark)` selector was defined last it was the one taking effect.

Example is working now: https://perfect-dark-mode-next.netlify.app/

**Comment by msglab** [comment]
Awesome! can confirm the demo works and I am now testing it in my application :) Thanks!
